#!/usr/bin/python3.7
'''
MyJpeg program. Encodes an 24-bit RGB image into a .myjpeg file, which must
then be decoded before it can be viewed.
'''

from src.encoder import encode, decode, transform
from src.constants import *

import argparse

def main(action, fp, destination, weights):
    weights_matrix = globals()[weights]
    if action == 'encode':
        encode(fp, destination, weights_matrix)
    elif action == 'decode':
        decode(fp, destination, weights_matrix)
    elif action == 'transform':
        transform(fp, destination, weights_matrix)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='compress some 24-bit images')
    subparsers = parser.add_subparsers(title='action',
                                       dest='action',
                                       metavar='action')

    # NOTE: Should I just put everything in one parser? All args are the same
    commands = [
            subparsers.add_parser('encode'),
            subparsers.add_parser('decode'),
            subparsers.add_parser('transform'),
    ]
    for p in commands: 
        p.add_argument('fp',
                       type=str,
                       metavar='input',
                       help='the file to be encoded')
        p.add_argument('destination',
                       type=str,
                       metavar='dest',
                       help='the output filename')
        p.add_argument('--weights',
                       '-w',
                       default='WEIGHTS_DEFAULT',
                       choices=WEIGHTS,
                       help='custom weights used for truncating terms')
    args = vars(parser.parse_args())
    if args['action']==None:
        parser.print_help()
    else:
        main(**args)
